import { chromium } from '/home/yuri/projects/ss/frontend/node_modules/playwright-core/index.mjs';
import pg from '/home/yuri/projects/ss/node_modules/pg/lib/index.js';
import dotenv from '/home/yuri/projects/ss/node_modules/dotenv/lib/main.js';
import fs from 'node:fs/promises';

dotenv.config({ path: '/home/yuri/projects/ss/.env', quiet: true });
const { Client } = pg;
const artifact='/home/yuri/projects/ss/qa-artifacts/run-b-20260711-195750', baseUrl='http://127.0.0.1:3000';
const email='qa-b2-guest-1783792954184@example.test', password='QA-B2-Claim!123', orderId='f1a571a5-64e7-48ad-891e-ff2ded33696c';
const subs={p1:'e8618e2c-37a0-4661-bfe1-995125820b7b',p2:'e869bdd6-d17e-49a2-a602-964dbec01785',p3:'3d147a02-f654-40dc-9c88-661d8a483ca7'};
const customerToken=(await fs.readFile(`${artifact}/customer-token.txt`,'utf8')).trim();
const db=new Client({host:process.env.DB_HOST,port:Number(process.env.DB_PORT||5432),database:process.env.DB_DATABASE,user:process.env.DB_USER,password:process.env.DB_PASSWORD}); await db.connect();
const record=row=>fs.appendFile(`${artifact}/phase3-steps.jsonl`,`${JSON.stringify({phase:3,...row})}\n`); let shot=35;
const snap=async(page,name)=>{const p=`screenshots/${String(++shot).padStart(3,'0')}-phase3-${name}.png`;await page.screenshot({path:`${artifact}/${p}`,fullPage:true});return p;};
const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
const context=await browser.newContext({viewport:{width:1440,height:1000},userAgent:'QA-B2-Chromium-UA/1.0'}); await context.addCookies([{name:'auth_token',value:customerToken,url:`${baseUrl}/`},{name:'csrf_token',value:'qa-b2-csrf',url:`${baseUrl}/`}]); const page=await context.newPage(); page.setDefaultTimeout(30000); const dialogs=[]; page.on('dialog',async d=>{dialogs.push(d.message());await d.dismiss();});
try{
 await page.goto(`${baseUrl}/dashboard/orders`,{waitUntil:'domcontentloaded',timeout:60000});
 const consent=page.getByRole('button',{name:'Reject non-essential'});if(await consent.isVisible({timeout:3000}).catch(()=>false))await consent.click();
 const p1=page.getByText('Qa B2 Streaming Plan (6 months)',{exact:true}).last().locator('xpath=ancestor::div[contains(@class,"rounded-lg")][1]');
 const before=Number((await db.query('SELECT count(*) FROM credential_reveal_audit_logs WHERE subscription_id=$1',[subs.p1])).rows[0].count);const rp=page.waitForResponse(r=>new URL(r.url()).pathname===`/api/v1/orders/${orderId}/items/${subs.p1}/reveal`);await p1.getByRole('button',{name:'Reveal'}).click();const rr=await rp;await page.getByText(/QA-B2 P1 fulfilled access/).waitFor();const after=Number((await db.query('SELECT count(*) FROM credential_reveal_audit_logs WHERE subscription_id=$1',[subs.p1])).rows[0].count);const ev1=(await db.query("SELECT event_type,license_account_access_evidence,metadata,ip_address FROM order_compliance_evidence_logs WHERE order_id=$1 AND license_account_access_evidence->>'subscription_id'=$2 ORDER BY created_at DESC LIMIT 1",[orderId,subs.p1])).rows[0];
 await record({action:'P1 per-item reveal',expected:'Exactly P1 credential and UA audits',actual:`HTTP ${rr.status()}, audit ${before}→${after}, evidence=${JSON.stringify(ev1)}`,result:rr.ok()&&after===before+1&&JSON.stringify(ev1).includes('QA-B2-Chromium-UA/1.0')?'PASS':'FAIL',evidence:await snap(page,'p1-reveal')});
 const p2=page.getByText('Qa B2 Ai Tool Qa B2 Ai Annual (12 months)',{exact:true}).last().locator('xpath=ancestor::div[contains(@class,"rounded-lg")][1]');await p2.getByRole('button',{name:'Reveal'}).click();const modal=page.getByRole('heading',{name:'Rules acknowledgement'}).locator('xpath=..');const rules=await modal.innerText();const accept=modal.getByRole('button',{name:'Accept'});const blocked=await accept.isDisabled();await modal.getByRole('checkbox').check();const ap=page.waitForResponse(r=>new URL(r.url()).pathname===`/api/v1/orders/${orderId}/items/${subs.p2}/accept-rules`);const rvp=page.waitForResponse(r=>new URL(r.url()).pathname===`/api/v1/orders/${orderId}/items/${subs.p2}/reveal`);await accept.click();const ar=await ap,rv=await rvp;await page.getByText(/QA-B2 P2 fulfilled access/).waitFor();const acc=(await db.query("SELECT event_type,license_account_access_evidence,metadata,ip_address FROM order_compliance_evidence_logs WHERE order_id=$1 AND event_type='strict_rules_acceptance' ORDER BY created_at DESC LIMIT 1",[orderId])).rows[0];
 await record({action:'P2 strict-rules XSS-safe acknowledgment and reveal',expected:'Literal script inert; checkbox gate; version evidence; reveal',actual:`literal=${rules.includes('<script>alert(1)</script>')}; dialogs=${dialogs.length}; blocked=${blocked}; accept=${ar.status()}; reveal=${rv.status()}; evidence=${JSON.stringify(acc)}`,result:rules.includes('<script>alert(1)</script>')&&dialogs.length===0&&blocked&&ar.ok()&&rv.ok()?'PASS':'FAIL',evidence:await snap(page,'p2-reveal')});
 await p2.getByRole('button',{name:'Hide'}).click();await p2.getByRole('button',{name:'Reveal'}).click();const repeated=await page.getByRole('heading',{name:'Rules acknowledgement'}).isVisible().catch(()=>false);await record({action:'Second P2 reveal after accepted rules',expected:'Modal skipped and new reveal audit',actual:repeated?'Rules modal appeared again':'Modal skipped',result:repeated?'FAIL':'PASS',evidence:await snap(page,'p2-second-reveal')});if(repeated)await page.getByRole('button',{name:'Cancel'}).click();
 const p3=page.getByText('Qa B2 Link Product Qa B2 Link Annual (12 months)',{exact:true}).last().locator('xpath=ancestor::div[contains(@class,"rounded-lg")][1]');const ready=p3.getByRole('button',{name:"I'm ready to activate"});const rb=await ready.isDisabled();await p3.getByRole('checkbox').check();const rdp=page.waitForResponse(r=>new URL(r.url()).pathname===`/api/v1/orders/${orderId}/items/${subs.p3}/activation-ready`);await ready.click();const rdr=await rdp;await p3.getByText('Activation readiness sent.',{exact:true}).waitFor();const rdb=(await db.query('SELECT activation_handshake_state FROM subscriptions WHERE id=$1',[subs.p3])).rows[0];const rev=(await db.query("SELECT event_type,license_account_access_evidence,metadata,ip_address FROM order_compliance_evidence_logs WHERE order_id=$1 AND license_account_access_evidence->>'subscription_id'=$2 ORDER BY created_at DESC LIMIT 1",[orderId,subs.p3])).rows[0];await record({action:'P3 mandatory-checkbox readiness',expected:'customer_ready and UA evidence',actual:`blocked=${rb}; HTTP ${rdr.status()}; DB=${JSON.stringify(rdb)}; evidence=${JSON.stringify(rev)}`,result:rb&&rdr.ok()&&rdb.activation_handshake_state==='customer_ready'&&JSON.stringify(rev).includes('QA-B2-Chromium-UA/1.0')?'PASS':'FAIL',evidence:await snap(page,'p3-ready')});
 await context.storageState({path:`${artifact}/phase3-customer-storage.json`});await fs.writeFile(`${artifact}/phase3-account.json`,JSON.stringify((await db.query('SELECT id,email FROM users WHERE email=$1',[email])).rows[0],null,2));
}finally{await context.close();await browser.close();await db.end();}
