import fs from 'node:fs'; import { createHmac } from 'node:crypto'; import jwt from 'jsonwebtoken'; import dotenv from 'dotenv'; import { Client } from 'pg';
dotenv.config({path:'.env',quiet:true}); const base='http://127.0.0.1:3104/api/v1', tag=`QA-A1-${Date.now()}`, out={tag,steps:{},ids:{}};
const sign=u=>jwt.sign({userId:u.id,email:u.email,role:u.role||'user'},process.env.JWT_SECRET,{algorithm:process.env.JWT_ALGORITHM||'HS256',expiresIn:'30m',issuer:'subscription-platform',audience:'subscription-platform-users'});
const admin=jwt.sign({userId:'c0dac6b4-c082-4fb6-9cd2-b6bc154160e2',email:'qa-admin-1768522228@example.test',role:'admin'},process.env.JWT_SECRET,{algorithm:process.env.JWT_ALGORITHM||'HS256',expiresIn:'30m',issuer:'subscription-platform',audience:'subscription-platform-users'});
async function q(path,{method='GET',body,token,headers={}}={}){const r=await fetch(base+path,{method,headers:{...(body?{'content-type':'application/json'}:{}),...(token?{cookie:`auth_token=${token}; csrf_token=qa`, 'x-csrf-token':'qa'}:{}),...headers},...(body?{body:typeof body==='string'?body:JSON.stringify(body)}:{})});const text=await r.text();let json;try{json=JSON.parse(text)}catch{}return{status:r.status,json,text}}
const d=r=>r.json?.data??r.json; const put=(n,r)=>{out.steps[n]={status:r.status,body:r.json};return r};
async function db(sql,v=[]){const c=new Client({host:process.env.DB_HOST,port:Number(process.env.DB_PORT||5432),database:process.env.DB_DATABASE,user:process.env.DB_USER,password:process.env.DB_PASSWORD});await c.connect();try{return(await c.query(sql,v)).rows}finally{await c.end()}}
async function reg(label){const email=`${tag.toLowerCase()}-${label}@example.test`,r=put(`register-${label}`,await q('/auth/register',{method:'POST',body:{email,password:'QaPassword!123',firstName:'QA',lastName:label}}));if(![200,201,202].includes(r.status))throw Error(`register ${label}`);return{...d(r).user,email,role:'user'}}
async function main(){const a=await reg('a'),b=await reg('b');out.ids.a=a.id;out.ids.b=b.id;const ta=sign(a),tb=sign(b);
const p=d(put('product',await q('/admin/products',{method:'POST',token:admin,body:{name:`${tag} strict`,slug:`${tag.toLowerCase()}-strict`,service_type:'qa_a1',default_currency:'USD',status:'inactive',metadata:{upgrade_options:{strict_rules:true,strict_rules_version:1,strict_rules_text:`${tag} rules`,activation_link_handshake:true,activation_instructions_template:`${tag} instructions`}}}})));out.ids.product=p.id;
const v=d(put('variant',await q('/admin/product-variants',{method:'POST',token:admin,body:{product_id:p.id,name:`${tag} variant`,variant_code:`${tag}-V`,service_plan:'qa',is_active:true}})));out.ids.variant=v.id;
put('term',await q('/admin/product-variant-terms',{method:'POST',token:admin,body:{product_variant_id:v.id,months:6,discount_percent:0,is_active:true}}));put('price',await q('/admin/price-history/current',{method:'POST',token:admin,body:{product_variant_id:v.id,price_cents:1000,currency:'USD',end_previous:true}}));put('activate',await q(`/admin/products/${p.id}`,{method:'PATCH',token:admin,body:{status:'active'}}));out.price_snapshot=await db(`SELECT ph.metadata->>'snapshot_id' snapshot_id,ppr.status FROM price_history ph JOIN pricing_publish_runs ppr ON ppr.snapshot_id=(ph.metadata->>'snapshot_id')::uuid WHERE ph.product_variant_id=$1 ORDER BY ph.starts_at DESC LIMIT 1`,[v.id]);
const ir=put('identity-registered',await q('/checkout/identity',{method:'POST',body:{email:a.email}})), iu=put('identity-unregistered',await q('/checkout/identity',{method:'POST',body:{email:`${tag.toLowerCase()}-unknown@example.test`}}));out.identity_shape_equivalent={status:ir.status===iu.status,fields:JSON.stringify(Object.keys(d(ir)).sort())===JSON.stringify(Object.keys(d(iu)).sort())};
const draft=d(put('guest-draft',await q('/checkout/draft',{method:'POST',body:{guest_identity_id:d(ir).guest_identity_id,contact_email:a.email,currency:'USD',items:[{variant_id:v.id,term_months:6,auto_renew:false}]}})));out.ids.order=draft.order_id;
const event=JSON.stringify({id:`evt_${tag}`,object:'event',type:'checkout.session.completed',data:{object:{id:`cs_${tag}`,object:'checkout.session',payment_intent:`pi_${tag}`,amount_total:draft.pricing.order_total_cents,currency:'usd',metadata:{order_id:draft.order_id}}}}),t=Math.floor(Date.now()/1000),sig=createHmac('sha256',process.env.STRIPE_WEBHOOK_SECRET).update(`${t}.${event}`).digest('hex');put('stripe-webhook',await q('/payments/stripe/webhook',{method:'POST',body:event,headers:{'content-type':'application/json','stripe-signature':`t=${t},v1=${sig}`}}));
const file=d(put('admin-order',await q(`/admin/next/orders/${draft.order_id}`,{token:admin}))),sub=file.items?.[0]?.subscription_id;if(!sub)throw Error('subscription missing');out.ids.subscription=sub;put('credentials-save',await q(`/admin/subscriptions/${sub}/credentials`,{method:'POST',token:admin,body:{credentials:`${tag}-secret`,reason:'QA-A1'}}));put('deliver',await q(`/admin/orders/${draft.order_id}/items/${sub}/deliver`,{method:'POST',token:admin,body:{reason:'QA-A1'}}));
const log=fs.readFileSync('qa-artifacts/run-a-final-20260711-000239/live-backend.log','utf8'),token=[...log.matchAll(/checkout\/claim\?token=([a-f0-9]{64})/g)].at(-1)?.[1];if(!token)throw Error('full claim token absent');out.claim_token_length=token.length;put('claim-mismatch',await q('/checkout/claim',{method:'POST',token:tb,body:{token}}));put('claim-no-token',await q('/checkout/claim',{method:'POST',body:{token}}));put('claim-owner',await q('/checkout/claim',{method:'POST',token:ta,body:{token}}));put('claim-double',await q('/checkout/claim',{method:'POST',token:ta,body:{token}}));put('owner-order',await q(`/orders/${draft.order_id}`,{token:ta}));
const before=await db('SELECT count(*)::int n FROM credential_reveal_audit_logs WHERE subscription_id=$1',[sub]);put('reveal-before-rules',await q(`/orders/${draft.order_id}/items/${sub}/reveal`,{method:'POST',token:ta,body:{}}));put('accept-false',await q(`/orders/${draft.order_id}/items/${sub}/accept-rules`,{method:'POST',token:ta,body:{confirmed:false}}));put('accept-missing',await q(`/orders/${draft.order_id}/items/${sub}/accept-rules`,{method:'POST',token:ta,body:{}}));put('accept-true',await q(`/orders/${draft.order_id}/items/${sub}/accept-rules`,{method:'POST',token:ta,body:{confirmed:true},headers:{'user-agent':'QA-A1-Accept'}}));put('reveal-ua',await q(`/orders/${draft.order_id}/items/${sub}/reveal`,{method:'POST',token:ta,body:{},headers:{'user-agent':'QA-A1-UA/1.0'}}));put('reveal-null-ua',await q(`/orders/${draft.order_id}/items/${sub}/reveal`,{method:'POST',token:ta,body:{},headers:{'user-agent':''}}));out.reveal_audit={before:before[0],rows:await db('SELECT user_agent,ip_address FROM credential_reveal_audit_logs WHERE subscription_id=$1 ORDER BY created_at DESC LIMIT 2',[sub]),evidence:await db("SELECT event_type,metadata FROM order_compliance_evidence_logs WHERE order_id=$1 AND event_type='credential_reveal' ORDER BY created_at DESC LIMIT 2",[draft.order_id])};
for(const[n,path,body]of[['idor-reveal',`/orders/${draft.order_id}/items/${sub}/reveal`,{}],['idor-accept',`/orders/${draft.order_id}/items/${sub}/accept-rules`,{confirmed:true}],['idor-ready',`/orders/${draft.order_id}/items/${sub}/activation-ready`,{confirmed:true}]])put(n,await q(path,{method:'POST',token:tb,body}));out.idor_after=await db('SELECT count(*)::int n FROM credential_reveal_audit_logs WHERE subscription_id=$1',[sub]);
put('ready-outside-awaiting',await q(`/orders/${draft.order_id}/items/${sub}/activation-ready`,{method:'POST',token:ta,body:{confirmed:true}}));put('customer-admin-instructions',await q(`/admin/orders/${draft.order_id}/items/${sub}/activation-instructions`,{method:'POST',token:ta,body:{instructions:'x'}}));put('admin-instructions',await q(`/admin/orders/${draft.order_id}/items/${sub}/activation-instructions`,{method:'POST',token:admin,body:{instructions:'QA-A1 instructions'}}));put('ready-first',await q(`/orders/${draft.order_id}/items/${sub}/activation-ready`,{method:'POST',token:ta,body:{confirmed:true}}));put('ready-second',await q(`/orders/${draft.order_id}/items/${sub}/activation-ready`,{method:'POST',token:ta,body:{confirmed:true}}));
const x=n=>'x'.repeat(n);put('limit-credentials',await q(`/admin/subscriptions/${sub}/credentials`,{method:'POST',token:admin,body:{credentials:x(6001)}}));put('limit-instructions',await q(`/admin/orders/${draft.order_id}/items/${sub}/activation-instructions`,{method:'POST',token:admin,body:{instructions:x(6001)}}));put('limit-note',await q(`/admin/orders/${draft.order_id}/mark-paid`,{method:'POST',token:admin,body:{note:x(1001)}}));put('limit-rules',await q(`/admin/products/${p.id}`,{method:'PATCH',token:admin,body:{metadata:{upgrade_options:{strict_rules_text:x(8001)}}}}));put('search-sqli',await q(`/admin/next/search?q=${encodeURIComponent("' OR 1=1 --")}`,{token:admin}));put('search-script',await q(`/admin/next/search?q=${encodeURIComponent('<script>alert(1)</script>')}`,{token:admin}));out.storage=await db('SELECT credentials_encrypted FROM subscriptions WHERE id=$1',[sub]);console.log(JSON.stringify(out,null,2));}
main().catch(e=>{out.error=e.stack;console.log(JSON.stringify(out,null,2));process.exitCode=1});
