export interface EnvironmentConfig {
  NODE_ENV: 'development' | 'production' | 'test';
  PORT: number;
  DB_HOST: string;
  DB_PORT: number;
  DB_DATABASE: string;
  DB_USER: string;
  DB_PASSWORD: string;
  DB_IDLE_IN_TRANSACTION_TIMEOUT_MS: number;
  SUPABASE_URL: string;
  SUPABASE_ANON_KEY: string;
  SUPABASE_SERVICE_ROLE_KEY: string;
  REDIS_HOST: string;
  REDIS_PORT: number;
  REDIS_PASSWORD?: string | undefined;
  REDIS_DB: number;
  REDIS_RATE_LIMIT_DB: number;
  REDIS_TTL_DEFAULT: number;
  REDIS_SESSION_TTL: number;
  REDIS_MAX_RETRIES: number;
  REDIS_RETRY_DELAY: number;
  JWT_SECRET: string;
  JWT_EXPIRY: number;
  JWT_ALGORITHM: 'HS256' | 'RS256';
  STRIPE_SECRET_KEY: string;
  STRIPE_WEBHOOK_SECRET: string;
  COOKIE_SECRET: string;
  SESSION_ENCRYPTION_KEY: string;
  SESSION_IV_LENGTH: number;
  CREDENTIALS_ENCRYPTION_KEY: string;
  CREDENTIALS_IV_LENGTH: number;
  MAX_SESSIONS_PER_USER: number;
  SESSION_CLEANUP_INTERVAL: number;
  NOWPAYMENTS_API_KEY: string;
  NOWPAYMENTS_SANDBOX_API_KEY?: string | undefined;
  NOWPAYMENTS_IPN_SECRET: string;
  NOWPAYMENTS_BASE_URL: string;
  NOWPAYMENTS_SANDBOX_MODE: boolean;
  NOWPAYMENTS_WEBHOOK_URL: string;
  NOWPAYMENTS_CURRENCY_CACHE_TTL: number;
  NOWPAYMENTS_CURRENCY_LKG_TTL: number;
  NOWPAYMENTS_CURRENCY_REFRESH_INTERVAL: number;
  PASSWORD_RESET_REDIRECT_URL?: string | undefined;
  APP_BASE_URL?: string | undefined;
  TIKTOK_EVENTS_ACCESS_TOKEN?: string | undefined;
  TIKTOK_PIXEL_ID: string;
  EMAIL_PROVIDER: 'smtp' | 'console' | 'resend';
  EMAIL_FROM?: string | undefined;
  EMAIL_REPLY_TO?: string | undefined;
  RESEND_API_KEY?: string | undefined;
  SMTP_HOST?: string | undefined;
  SMTP_PORT?: number | undefined;
  SMTP_SECURE: boolean;
  SMTP_USER?: string | undefined;
  SMTP_PASSWORD?: string | undefined;
  SMTP_CONNECTION_TIMEOUT: number;
  SMTP_GREETING_TIMEOUT: number;
  SMTP_SOCKET_TIMEOUT: number;
  PASSWORD_RESET_EMAIL_SUBJECT: string;
  CATALOG_DB_PRICING: boolean;
  COUPON_RESERVATION_MINUTES: number;
  CHECKOUT_ABANDON_TTL_MINUTES: number;
  CHECKOUT_ABANDON_SWEEP_INTERVAL: number;
  CHECKOUT_ABANDON_SWEEP_BATCH_SIZE: number;

  // Payment Monitoring Configuration
  PAYMENT_MONITORING_INTERVAL: number;
  PAYMENT_MONITORING_BATCH_SIZE: number;
  PAYMENT_RETRY_ATTEMPTS: number;
  PAYMENT_RETRY_DELAY: number;

  // Credit Allocation Settings
  CREDIT_ALLOCATION_RATE: number;
  CREDIT_ALLOCATION_TIMEOUT: number;

  // Refund Processing Configuration
  REFUND_APPROVAL_REQUIRED: boolean;
  REFUND_PROCESSING_TIMEOUT: number;

  // Background Jobs / Monitors
  JOBS_ENABLED: boolean;
  PAYMENT_MONITORING_AUTO_START: boolean;
  SUBSCRIPTION_RENEWAL_INTERVAL: number;
  SUBSCRIPTION_RENEWAL_LOOKAHEAD_MINUTES: number;
  SUBSCRIPTION_RENEWAL_BATCH_SIZE: number;
  SUBSCRIPTION_RENEWAL_RETRY_MINUTES: number;
  SUBSCRIPTION_EXPIRY_INTERVAL: number;
  SUBSCRIPTION_REMINDER_INTERVAL: number;
  UPGRADE_SELECTION_REMINDER_INTERVAL: number;
  MANUAL_MONTHLY_UPGRADE_INTERVAL: number;
  PIN_LOCKOUT_MONITOR_INTERVAL: number;
  SUBSCRIPTION_DATA_QUALITY_INTERVAL: number;
  CONTEST_PRIZE_INTERVAL: number;
  VIRAL_METRICS_INTERVAL: number;
  EMAIL_VERIFICATION_SYNC_INTERVAL: number;
  EMAIL_VERIFICATION_SYNC_BATCH_SIZE: number;
}
