import fs from 'node:fs'; import jwt from 'jsonwebtoken'; import dotenv from 'dotenv'; import { Client } from 'pg';
dotenv.config({path:'.env',quiet:true}); const prior=JSON.parse(fs.readFileSync('qa-artifacts/run-a-final-20260711-000239/live-probes.json')); const base='http://127.0.0.1:3104/api/v1',out={steps:{},ids:prior.ids}; const a=prior.steps['register-a'].body.user;
const admin=jwt.sign({userId:'c0dac6b4-c082-4fb6-9cd2-b6bc154160e2',email:'qa-admin-1768522228@example.test',role:'admin'},process.env.JWT_SECRET,{algorithm:'HS256',expiresIn:'30m',issuer:'subscription-platform',audience:'subscription-platform-users'}); const user=jwt.sign({userId:a.id,email:a.email,role:'user'},process.env.JWT_SECRET,{algorithm:'HS256',expiresIn:'30m',issuer:'subscription-platform',audience:'subscription-platform-users'});
async function q(path,{method='GET',body,token,headers={}}={}){const r=await fetch(base+path,{method,headers:{...(body?{'content-type':'application/json'}:{}),...(token?{cookie:`auth_token=${token};csrf_token=qa`,'x-csrf-token':'qa'}:{}),...headers},...(body?{body:JSON.stringify(body)}:{})});const text=await r.text();let json;try{json=JSON.parse(text)}catch{}return{status:r.status,json,text}} const put=(n,r)=>(out.steps[n]={status:r.status,body:r.json},r);async function db(s,v=[]){const c=new Client({host:process.env.DB_HOST,port:Number(process.env.DB_PORT||5432),database:process.env.DB_DATABASE,user:process.env.DB_USER,password:process.env.DB_PASSWORD});await c.connect();try{return(await c.query(s,v)).rows}finally{await c.end()}}
const o=prior.ids.order,s=prior.ids.subscription,p=prior.ids.product; async function main(){
for(const [n,path,body] of [['deliver',`/admin/orders/${o}/items/${s}/deliver`,{reason:'x'}],['instructions',`/admin/orders/${o}/items/${s}/activation-instructions`,{instructions:'x'}],['link',`/admin/orders/${o}/items/${s}/activation-link`,{}],['restart',`/admin/orders/${o}/items/${s}/activation-restart`,{}],['mmu-creds',`/admin/tasks/${s}/credentials`,null],['next-orders','/admin/next/orders',null],['next-subs','/admin/next/subscriptions',null],['slim','/admin/next/users/slim?search=qa',null],['newsletter','/admin/next/coupons/newsletter',null],['search','/admin/next/search?q=qa',null],['queue','/admin/fulfillment/queue',null]]){put(`unauth-${n}`,await q(path,{method:body?'POST':'GET',body}));put(`customer-${n}`,await q(path,{method:body?'POST':'GET',body,token:user}));}
for(const[n,path]of[['reveal',`/orders/${o}/items/${s}/reveal`],['accept',`/orders/${o}/items/${s}/accept-rules`],['ready',`/orders/${o}/items/${s}/activation-ready`]])put(`unauth-${n}`,await q(path,{method:'POST',body:n==='accept'||n==='ready'?{confirmed:true}:{}}));
put('admin-sub-list',await q('/admin/next/subscriptions',{token:admin}));put('admin-sub-detail',await q(`/admin/next/subscriptions/${s}`,{token:admin}));put('fulfillment-detail',await q(`/admin/fulfillment/orders/${o}`,{token:admin}));const before=await db("SELECT count(*)::int n FROM admin_audit_logs WHERE action='subscriptions.credentials.view' AND entity_id=$1",[s]);put('admin-show',await q(`/admin/subscriptions/${s}/credentials`,{token:admin}));out.admin_show_after=await db("SELECT count(*)::int n FROM admin_audit_logs WHERE action='subscriptions.credentials.view' AND entity_id=$1",[s]);out.admin_show_before=before;
const x=n=>'x'.repeat(n);put('exact-creds',await q(`/admin/subscriptions/${s}/credentials`,{method:'POST',token:admin,body:{credentials:x(4000)}}));put('exact-instructions',await q(`/admin/orders/${o}/items/${s}/activation-instructions`,{method:'POST',token:admin,body:{instructions:x(4000)}}));put('exact-note',await q(`/admin/orders/${o}/mark-paid`,{method:'POST',token:admin,body:{note:x(1000)}}));put('exact-rules',await q(`/admin/products/${p}`,{method:'PATCH',token:admin,body:{metadata:{upgrade_options:{strict_rules_text:x(8000)}}}}));
console.log(JSON.stringify(out,null,2));}main().catch(e=>{out.error=e.stack;console.log(JSON.stringify(out,null,2));process.exitCode=1});
